---
# tasks file for cdh-opti
- name: Include OS-specific variables.
  include_vars: '{{ ansible_os_family }}.yml'
  
- name: Include optimized network settings
  include_vars: 'network.yml'
  
- name: Include limits
  include_vars: 'limits.yml'
  
- include: proxy.yml
- include: huge-pages.yml
- include: vm-swappiness.yml
- include: network.yml
- include: mounts.yml
- include: limits.yml
- include: selinux.yml
- include: iptables.yml